// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCIfesObgDNqLV2jIc7HW6Ut1POOArGl4',
    appId: '1:580871116724:web:53c886fa5eadd7512f84e1',
    messagingSenderId: '580871116724',
    projectId: 'socialcharity-10473',
    authDomain: 'socialcharity-10473.firebaseapp.com',
    storageBucket: 'socialcharity-10473.firebasestorage.app',
    measurementId: 'G-NFWQ2ZX3RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlaT-0H6KzYmb8_snoMCvtzCEUNofAZP4',
    appId: '1:580871116724:android:7e9c2e7311dd64c62f84e1',
    messagingSenderId: '580871116724',
    projectId: 'socialcharity-10473',
    storageBucket: 'socialcharity-10473.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhYl4ufancFyUgtAiMI7I0SkRxuGCjjvI',
    appId: '1:580871116724:ios:d7d7c63fb18eb42c2f84e1',
    messagingSenderId: '580871116724',
    projectId: 'socialcharity-10473',
    storageBucket: 'socialcharity-10473.firebasestorage.app',
    iosBundleId: 'com.example.tester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhYl4ufancFyUgtAiMI7I0SkRxuGCjjvI',
    appId: '1:580871116724:ios:d7d7c63fb18eb42c2f84e1',
    messagingSenderId: '580871116724',
    projectId: 'socialcharity-10473',
    storageBucket: 'socialcharity-10473.firebasestorage.app',
    iosBundleId: 'com.example.tester',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCIfesObgDNqLV2jIc7HW6Ut1POOArGl4',
    appId: '1:580871116724:web:8db8727f7479dbb82f84e1',
    messagingSenderId: '580871116724',
    projectId: 'socialcharity-10473',
    authDomain: 'socialcharity-10473.firebaseapp.com',
    storageBucket: 'socialcharity-10473.firebasestorage.app',
    measurementId: 'G-5D11B7ME5R',
  );

}
