name: tester
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_database: ^10.4.6
  image_picker: ^0.8.7+3
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  mysql1: ^0.20.0
  http: ^1.2.2
  url_launcher: ^6.1.5
  lottie: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/rectangle_18.png
    - assets/logo.png
    - assets/mat.png
    - assets/thu.png
    - assets/okhoa.png
    - assets/cccd.png
    - assets/quaylai.png
    - assets/welcome.png
    - assets/logoGG.png
    - assets/logoFB.png
    - assets/thongbaodangky.png
    - assets/thongbaodangky2.png
    - assets/Rectangle_36.png
    - assets/Rectangle_4.png
    - assets/location.png
    - assets/caidat.png
    - assets/danhmuc.png
    - assets/search.png
    - assets/trungbay.png
    - assets/Tab_Home.png
    - assets/Tab_XuHuong.png
    - assets/Tab_ThongBao.png
    - assets/Tab_TrangCaNhan.png
    - assets/giupdo.png
    - assets/chiase.png
    - assets/lichsu.png
    - assets/onghuy.png
    - assets/chuahoanthanh.png
    - assets/zalo.png
    - assets/clock.png
    - assets/hinhanhminhchung.png
    - assets/teamaisc.jpg
    - assets/profile1.png
    - assets/profile2.png
    - assets/profile3.png
    - assets/profile4.png
    - assets/profile5.png
    - assets/mayanh.png
    - assets/caidatvang.png
    - assets/about.png
    - assets/logout.png
    - assets/help.png
    - assets/chat.png
    - assets/phoneprofile.png
    - assets/xanh.png
    - assets/list_tien.png
    - assets/taianhlen.png
    - assets/quaylai2.png
    - assets/search2.png
    - assets/giohang.png
    - assets/HinhAnh_0.png
    - assets/HinhAnh1.png
    - assets/HinhAnh_2.png
    - assets/danhmuc2.png
    - assets/nguoikhokhan1.jpg
    - assets/nguoikhokhan2.jpg
    - assets/nguoikhokhan3.jpg
    - assets/nguoikhokhan4.jpg
    - assets/nguoikhokhan5.jpg
    - assets/nguoikhokhan6.jpg
    - assets/nguoikhokhan7.jpg
    - assets/nguoikhokhan8.jpg
    - assets/nguoikhokhan9.jpg
    - assets/dahoanthanh.png
    - assets/HinhAnh_Demo.jpg
    - assets/HinhAnh_Demo1.jpg
    - assets/HinhAnh_Demo2.jpeg
    - assets/HinhAnh_Demo3.jpg
    - assets/icon_password.png
    - assets/icon_fb.png
    - assets/ic_gg.png
    - assets/AnhCV.jpg
    - assets/sapa2_welcome.jpg
    - assets/sapa4_welcome.jpg
    - assets/sapa41_welcome.jpg
    - assets/images/user1.png
    - assets/images/user2.png
    - assets/images/user3.jpg
    - assets/images/user4.png
    - assets/images/user5.jpg
    - assets/images/user6.png
    - assets/images/user7.jpg
    - assets/images/user8.png
    - assets/images/chiendich1.jpg
    - assets/images/chiendich2.jpg
    - assets/images/chiendich3.jpg
    - assets/images/chiendich4.jpg
    - assets/images/chiendich5.jpg
    - assets/images/chiendich6.jpg
    - assets/images/chiendich7.jpg
    - assets/images/chiendich8.jpg
    - assets/images/chiendich9.jpg
    - assets/images/chiendich8.jpg
    - assets/images/chiendich10.jpg
    - assets/images/sapa5_dangky.jpg
    - assets/images/sapa3_welcome.jpg
    - assets/images/sapa7.png
    - assets/images/sapa8.png
    - assets/images/ufm.jpg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
          weight: 700

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
